apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: pp1blts/main
      context: ../main
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
