export const enum AttentionItem {
  TEMP_LOW = 'TEMP_LOW',
  TEMP_HIGH = 'TEMP_HIGH',
  HUMIDITY_LOW = 'HUMIDITY_LOW',
  HUMIDITY_HIGH = 'HUMIDITY_HIGH',
  LIGHT_LOW = 'LIGHT_LOW',
  LIGHT_HIGH = 'LIGHT_HIGH',
  MOISTURE_LOW = 'MOISTURE_LOW',
  MOISTURE_HIGH = 'MOISTURE_HIGH',
  NO_DATA = 'NO_DATA'
}
